spring:
  name: welcome-app
  description: This is my first app
  profiles:
    active:
  officialGreeting: Good Morning
  unofficialGreeting: Hello

management:
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info